from django.urls import path ,re_path
from app.views import*
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    ###############GALARY UPDATE#######################    
    path('s-admin/',Admin_Page,name='admin_panel_index'),
    path('contact/',User_Contact_for_Admin,name='user-data-contact'),
    path('admin-post/',Admin_Post,name='admin_post'),                     
    path('Admin-Post-View/',Admin_Post_View,name='Admin_Post_View'),
    path('Admin-Post-Delete/<slug:post_id>/',Admin_Post_Delete,name='Admin_Post_Delete'),
    path('Admin-Post-Edit/<slug:edit_id>/',Admin_Post_Edit,name='Admin_Post_edit'),
    path('Admin-Post-Update/',Admin_Update,name='Admin_Post_Update'),
    path('Admin-Contact-Delete/<slug:contact_id>/', User_Contact_for_Admin_Delete,name='User_Contact_for_Admin_Delete'),
    path('user-login/', User_login,name='admin_login'),
    path('user-logout/', logout_user,name='admin_logout'),
    path('user-update-profile/<slug:Profile_id>', User_Admin_Update_Profile,name='User_Admin_Update_Profile'),
    path('user-update-profile/', User_Admin_Finaly_Update_Profile,name='User_Admin_Finaly_Update_Profile'),
    path('search-query/' ,search,name='search'),
    path('download/<slug:download_id>' ,Download,name='Download'),
    path('Admin-Create-Category/' ,Admin_Create_Category,name='Admin_Create_Category'),
    path('Admin-Views-Category/' , Admin_Category_View,name='Admin_Category_View'),
    path('Admin-Category-Delete/<slug:cate_id>' , Admin_Category_Delete,name='Admin_Category_Delete'),
    path('Admin-Category-Edit/<slug:category_id>' , Admin_Category_Edit,name='Admin_Category_Edit'),
    path('Admin-Category-Update/' , Admin_Category_Update,name='Admin_Category_Update'),
    path('Admin-Evant-post/' , User_Evant_post,name='User_Evant_post'),
    path('Admin-Evant-edit/<int:id>' , User_Evant_post_Edit,name='User_Evant_post_Edit'),
    path('Admin-Evant-Update/' , user_Evant_Update,name='user_Evant_Update'),

    
    
    
    

    
     


    



    ###############USER ####################### 
    path('',User_Index,name='User_Index'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    path('About/',User_About,name='User_About'),
    path('cs-galary/',User_Causes,name='User_Causes'),  
    path('cs-galary/<slug:data>/',User_Causes,name='User_Causesgetmethed'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    
    
    path('cs-Contact/',User_Contact,name='User_Contact'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    path('Donation/',User_Donation,name='User_Donation'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    path('Education/',User_Education,name='User_Education'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    path('Eventdetails/',User_Eventdetails,name='User_Eventdetails'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    path('Events/',User_Events,name='User_Events'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    path('Faq/',User_Faq,name='User_Faq'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    path('Health/',User_Health,name='User_Health'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    path('Marriage/',User_Marriage,name='User_Marriage'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    path('Newsdetails/',User_Newsdetails,name='User_Newsdetails'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    path('Outproduct/',User_Outproduct,name='User_Outproduct'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    path('Team/',User_Team,name='User_Team'), 
    # path('pro-galarys/',Galary,name='User_Causes_All'), 
    # path('pro-galary/<slug:data>/',Galary,name='galarydata'), 


    

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    


    

    

    

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
